### ISSUE TITLE
Free Live TV no more working

### ISSUE THREAD

**Issue by Max11223344** [mhancoc7/kodi-addons#11]
**Describe the bug**
Starting today Free Live TV crashes when starting.
(Starting 'Kodi' --> Video Addons --> Free Live TV

**Expected behavior**
Free Live TV starts (Yesterday it was working fine ... Kodi Leia 18.7 on Raspi 4 4GB

**Debug Log**
Here is the Kodi Log

2021-09-09 13:07:00.100 T:2369966288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.freelivetv.tva/default.py", line 29, in <module>
                                                Channels.channel_list()
                                              File "/home/pi/.kodi/addons/plugin.video.freelivetv.tva/resources/lib/modules/channels.py", line 35, in channel_list
                                                for channel in m7lib.Common.get_channels():
                                              File "/home/pi/.kodi/addons/script.module.m7lib/lib/m7lib.py", line 108, in get_channels
                                                req = Common.open_url(base64.b64decode(stream_plug).decode("UTF-8") + "index.json")
                                              File "/home/pi/.kodi/addons/script.module.m7lib/lib/m7lib.py", line 100, in open_url
                                                response = urlopen(req)  # nosec
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
                                            -->End of Python script error report<--
2021-09-09 13:07:00.326 T:2378358992   ERROR: GetDirectory - Error getting plugin://plugin.video.freelivetv.tva/
2021-09-09 13:07:00.328 T:2972535904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freelivetv.tva/) failed

(could this be a problem with inputstream? I know the Kodi Crew is making changes to inputstream adaptive...).

**Comment by jeremehancock** [comment]
Thank you for letting me know. The issue was actually an issue with an SSL certificate in one of the systems that powers Free Live TV. I have resolved that issue. Please let me know if you are still seeing the issue. I am going to close this Issue since I was able to replicate the issue and the resolution. Please feel free to open a new Issue if you still have any issues. Thanks again

**Comment by Max11223344** [comment]
Wow! That was fast :-)
Thank you very much for the fast repair. It is working again.

Once more: Thank you!

**Comment by jeremehancock** [comment]
No worries. I am just glad it was an easy fix. ;)
