### ISSUE TITLE
UKTV Play no longer working

### ISSUE THREAD

**Issue by techionltd** [mhancoc7/kodi-addons#2]
Unable to get past list of channels.
Kodi log shows :- 

20:55:22.592 T:139955013584640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.bhg.uktvplay/default.py", line 94, in <module>
                                                elif mode==10: vod_uktv(url)
                                              File "/home/kodi/.kodi/addons/plugin.video.bhg.uktvplay/resources/lib/modules/uktv_play.py", line 36, in vod_uktv
                                                link = open_url(url)
                                              File "/home/kodi/.kodi/addons/plugin.video.bhg.uktvplay/resources/lib/modules/common.py", line 49, in open_url
                                                response = opener.open(req,data=data)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                                result = self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                                return self.parent.open(new, timeout=req.timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
20:55:22.601 T:139955943197056   ERROR: GetDirectory - Error getting plugin://plugin.video.bhg.uktvplay/?mode=10&name=Dave&url=http%3a%2f%2fuktvplay.uktv.co.uk%2fshows%2fchannel%2fdave%2f
20:55:22.602 T:139955943197056   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bhg.uktvplay/?mode=10&name=Dave&url=http%3a%2f%2fuktvplay.uktv.co.uk%2fshows%2fchannel%2fdave%2f) failed

**Comment by jeremehancock** [comment]
I have decided to discontinue this addon. Thanks
